# Generated by Django 5.2.7 on 2025-11-13 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0006_materia_updated_at'),
        ('users', '0002_customuser_direccion_customuser_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='grado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='notas.grado'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='materias',
            field=models.ManyToManyField(blank=True, related_name='estudiantes', to='notas.materia'),
        ),
    ]
