# Generated by Django 5.2 on 2025-04-04 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acudiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docu_acudiente', models.IntegerField()),
                ('acu_nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('acu_apellido', models.CharField(blank=True, max_length=45, null=True)),
                ('acu_email', models.CharField(blank=True, max_length=45, null=True)),
                ('acu_tel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docu_profesor', models.IntegerField()),
                ('profe_especialidad', models.CharField(blank=True, max_length=45, null=True)),
                ('profe_email', models.CharField(blank=True, max_length=45, null=True)),
                ('profe_nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('profe_apellido', models.CharField(blank=True, max_length=45, null=True)),
                ('profe_escalafon', models.CharField(blank=True, max_length=45, null=True)),
                ('profe_area', models.CharField(blank=True, max_length=45, null=True)),
                ('profe_tel', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_type',
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docu_estudiante', models.IntegerField()),
                ('estu_nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('estu_apellido', models.CharField(blank=True, max_length=45, null=True)),
                ('estu_email', models.CharField(blank=True, max_length=45, null=True)),
                ('estu_tel', models.IntegerField()),
                ('acudiente_docu_acudiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.acudiente')),
                ('profesor_docu_profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profesor')),
            ],
        ),
    ]
