# Generated by Django 5.2 on 2025-06-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_acudiente_profesor_remove_customuser_user_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='directivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docu_directivo', models.IntegerField()),
                ('dire_nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('dire_apellido', models.CharField(blank=True, max_length=45, null=True)),
                ('dire_email', models.CharField(blank=True, max_length=45, null=True)),
                ('dire_tel', models.IntegerField()),
            ],
        ),
    ]
