# Generated by Django 5.2 on 2025-06-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_directivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tipo_usuario',
            field=models.CharField(choices=[('estudiante', 'Estudiante'), ('profesor', 'Profesor'), ('directivo', 'Directivo'), ('acudiente', 'Acudiente')], default='estudiante', max_length=20),
        ),
    ]
