# Generated by Django 5.2 on 2025-06-30 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acudiente',
            name='acu_tel',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='acudiente',
            name='docu_acudiente',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='directivo',
            name='dire_tel',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='directivo',
            name='docu_directivo',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='docu_estudiante',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='estu_tel',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='docu_profesor',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='profe_tel',
            field=models.BigIntegerField(),
        ),
    ]
