# Generated by Django 5.2 on 2025-06-30 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_acudiente_acu_tel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acudiente',
            name='acudiente_docu_acudiente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.acudiente'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='profesor_docu_profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profesor'),
        ),
    ]
