# Generated by Django 5.2 on 2025-06-30 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_acudiente_acudiente_docu_acudiente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acudiente',
            name='acudiente_docu_acudiente',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='profesor_docu_profesor',
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='acudiente_docu_acudiente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.acudiente'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='profesor_docu_profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profesor'),
        ),
    ]
