# Generated by Django 5.2.5 on 2025-09-07 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_customuser_direccion_customuser_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalaNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('minimo', models.DecimalField(decimal_places=2, max_digits=4)),
                ('maximo', models.DecimalField(decimal_places=2, max_digits=4)),
                ('paso', models.DecimalField(decimal_places=2, default=0.1, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='AnioEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('escala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anios_escolares', to='notas.escalanota')),
            ],
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('anio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grados', to='notas.anioescolar')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('grado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materias', to='notas.grado')),
                ('profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profesor')),
            ],
            options={
                'unique_together': {('nombre', 'grado')},
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('anio_escolar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='notas.anioescolar')),
            ],
            options={
                'unique_together': {('anio_escolar', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='InformeFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedio_final', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('anio_escolar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.anioescolar')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes_finales', to='users.estudiante')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes_finales', to='notas.materia')),
            ],
            options={
                'unique_together': {('estudiante', 'materia', 'anio_escolar')},
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='users.estudiante')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='notas.materia')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='notas.periodo')),
            ],
            options={
                'unique_together': {('estudiante', 'materia', 'periodo', 'descripcion')},
            },
        ),
    ]
