# Generated by Django 5.2.7 on 2025-11-20 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notas', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informefinal',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes_finales', to='users.estudiante'),
        ),
        migrations.AddField(
            model_name='materia',
            name='grado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materias', to='notas.grado'),
        ),
        migrations.AddField(
            model_name='materia',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profesor'),
        ),
        migrations.AddField(
            model_name='informefinal',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes_finales', to='notas.materia'),
        ),
        migrations.AddField(
            model_name='nota',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='users.estudiante'),
        ),
        migrations.AddField(
            model_name='nota',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='notas.materia'),
        ),
        migrations.AddField(
            model_name='periodo',
            name='anio_escolar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='notas.anioescolar'),
        ),
        migrations.AddField(
            model_name='nota',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='notas.periodo'),
        ),
        migrations.AddField(
            model_name='grado',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grados', to='notas.periodo'),
        ),
        migrations.AlterUniqueTogether(
            name='materia',
            unique_together={('nombre', 'grado')},
        ),
        migrations.AlterUniqueTogether(
            name='informefinal',
            unique_together={('estudiante', 'materia', 'anio_escolar')},
        ),
        migrations.AlterUniqueTogether(
            name='periodo',
            unique_together={('anio_escolar', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='nota',
            unique_together={('estudiante', 'materia', 'periodo', 'descripcion')},
        ),
    ]
