# Generated by Django 5.2 on 2025-09-29 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0002_alter_materia_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escalanota',
            name='maximo',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='escalanota',
            name='minimo',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='escalanota',
            name='paso',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=4),
        ),
    ]
