# Generated by Django 5.2.5 on 2025-10-29 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0003_alter_escalanota_maximo_alter_escalanota_minimo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grado',
            name='periodo',
            field=models.ManyToManyField(related_name='grados', to='notas.periodo'),
        ),
    ]
