# Generated by Django 5.2.5 on 2025-11-04 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0004_grado_periodo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grado',
            name='periodo',
        ),
        migrations.AddField(
            model_name='grado',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grados', to='notas.periodo'),
        ),
    ]
