-- MySQL Script generated by MySQL Workbench
-- Mon Apr 29 20:46:25 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema colegio
-- -----------------------------------------------------
-- Base de atos para la administracion de un colegio tipico en  Colombia

-- -----------------------------------------------------
-- Schema colegio
--
-- Base de atos para la administracion de un colegio tipico en  Colombia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `colegio` ;
USE `colegio` ;

-- -----------------------------------------------------
-- Table `colegio`.`profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colegio`.`profesor` (
  `docu_profesor` INT NOT NULL,
  `profe_especialidad` VARCHAR(45) NULL,
  `profe_email` VARCHAR(45) NULL,
  `profe_nombre` VARCHAR(45) NULL,
  `profe_apellido` VARCHAR(45) NULL,
  `profe_escalafon` VARCHAR(45) NULL,
  `profe_area` VARCHAR(45) NULL,
  `profe_tel` INT NULL,
  PRIMARY KEY (`docu_profesor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `colegio`.`escuela`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colegio`.`escuela` (
  `codigo_escuela` INT NOT NULL,
  `escuela_nombre` VARCHAR(45) NULL,
  `profesor_docu_profesor` INT NOT NULL,
  PRIMARY KEY (`codigo_escuela`),
  INDEX `fk_escuela_profesor1_idx` (`profesor_docu_profesor` ASC) VISIBLE,
  CONSTRAINT `fk_escuela_profesor1`
    FOREIGN KEY (`profesor_docu_profesor`)
    REFERENCES `colegio`.`profesor` (`docu_profesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `colegio`.`Sede`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colegio`.`Sede` (
  `codigo_sede` INT NOT NULL,
  `sede_nombre` VARCHAR(45) NULL,
  `escuela_codigo_escuela` INT NOT NULL,
  PRIMARY KEY (`codigo_sede`, `escuela_codigo_escuela`),
  INDEX `fk_Sede_escuela1_idx` (`escuela_codigo_escuela` ASC) VISIBLE,
  CONSTRAINT `fk_Sede_escuela1`
    FOREIGN KEY (`escuela_codigo_escuela`)
    REFERENCES `colegio`.`escuela` (`codigo_escuela`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `colegio`.`acudiente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colegio`.`acudiente` (
  `docu_acudiente` INT NOT NULL,
  `acu_nombre` VARCHAR(45) NULL,
  `acu_apellido` VARCHAR(45) NULL,
  `acu_email` VARCHAR(45) NULL,
  `acu_tel` INT NULL,
  PRIMARY KEY (`docu_acudiente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `colegio`.`estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colegio`.`estudiante` (
  `docu_estudiante` INT NOT NULL,
  `estu_nombre` VARCHAR(45) NULL,
  `estu_apellido` VARCHAR(45) NULL,
  `estu_email` VARCHAR(45) NULL,
  `estu_tel` INT NULL,
  `docu_profesor` INT NOT NULL,
  `acudiente_docu_acudiente` INT NOT NULL,
  PRIMARY KEY (`docu_estudiante`),
  INDEX `fk_estudiante_profesor_idx` (`docu_profesor` ASC) VISIBLE,
  INDEX `fk_estudiante_acudiente1_idx` (`acudiente_docu_acudiente` ASC) VISIBLE,
  CONSTRAINT `fk_estudiante_profesor`
    FOREIGN KEY (`docu_profesor`)
    REFERENCES `colegio`.`profesor` (`docu_profesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estudiante_acudiente1`
    FOREIGN KEY (`acudiente_docu_acudiente`)
    REFERENCES `colegio`.`acudiente` (`docu_acudiente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `colegio`.`materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colegio`.`materia` (
  `codigo_materia` INT NOT NULL,
  `materia_nombre` VARCHAR(45) NULL,
  `profesor_docu_profesor` INT NOT NULL,
  `estudiante_docu_estudiante` INT NOT NULL,
  PRIMARY KEY (`codigo_materia`, `estudiante_docu_estudiante`),
  INDEX `fk_materia_profesor1_idx` (`profesor_docu_profesor` ASC) VISIBLE,
  INDEX `fk_materia_estudiante1_idx` (`estudiante_docu_estudiante` ASC) VISIBLE,
  CONSTRAINT `fk_materia_profesor1`
    FOREIGN KEY (`profesor_docu_profesor`)
    REFERENCES `colegio`.`profesor` (`docu_profesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_materia_estudiante1`
    FOREIGN KEY (`estudiante_docu_estudiante`)
    REFERENCES `colegio`.`estudiante` (`docu_estudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `colegio`.`grado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colegio`.`grado` (
  `nombre` VARCHAR(24) NOT NULL,
  `codigo_grado` VARCHAR(3) NOT NULL,
  `materia_codigo_materia` INT NOT NULL,
  PRIMARY KEY (`codigo_grado`),
  INDEX `fk_grado_materia1_idx` (`materia_codigo_materia` ASC) VISIBLE,
  CONSTRAINT `fk_grado_materia1`
    FOREIGN KEY (`materia_codigo_materia`)
    REFERENCES `colegio`.`materia` (`codigo_materia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `colegio`.`salon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colegio`.`salon` (
  `codigo_salon` INT NOT NULL,
  `salon_nombre` VARCHAR(45) NULL,
  `Sede_codigo_sede` INT NOT NULL,
  `Sede_escuela_codigo_escuela` INT NOT NULL,
  PRIMARY KEY (`codigo_salon`, `Sede_codigo_sede`, `Sede_escuela_codigo_escuela`),
  INDEX `fk_salon_Sede1_idx` (`Sede_codigo_sede` ASC, `Sede_escuela_codigo_escuela` ASC) VISIBLE,
  CONSTRAINT `fk_salon_Sede1`
    FOREIGN KEY (`Sede_codigo_sede` , `Sede_escuela_codigo_escuela`)
    REFERENCES `colegio`.`Sede` (`codigo_sede` , `escuela_codigo_escuela`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
